### ISSUE TITLE
Not a Issue , this repo needs update!

### ISSUE THREAD

**Issue by mrbeandev** [sau412/coinhive_pool#5]
long time ago coinhive has stopped their service i just wanted to know is this is still working ?

**Comment by sau412** [comment]
Hi. There is coinimp (another web mining service) support was implemented as I remember, but I'm not sure it still working now (but should be).

I closed my site associated with that repo long ago, ant not updated it since then.

There is another team running their site based on this repo (they also rewrited multiple parts) - https://highpay-pool.com/
But they have closed sources.

**Comment by mrbeandev** [comment]
what should do here?
i didnt understand this point there > 🤔

"Download jquery to pool folder"

appreciate your help

and i cant find these in my coinimp account ?
where can i get these from ?
$coinimp_xmr_site_key="";
$coinimp_web_site_key="";

**Comment by sau412** [comment]
Download mininal jQuery lib from https://jquery.com/ and name it "jquery-3.3.1.min.js" in the project folder (or fix jquery lib version in html.php).

Those keys generated by coinimp site. Register at https://coinimp.com/

**Comment by mrbeandev** [comment]
thank you for the jquery help !

i edited the line in html.php with `<script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>`

i registered and added got only TWO keys public and private key , but i didnt got any key 🗝  labled as $coinimp_xmr_site_key="";
$coinimp_web_site_key=""; any of these

**Comment by mrbeandev** [comment]
and i will surely place a correct PR , if i find any errors in the ripo 👍

firstly i will try removing full coinhive codes

**Comment by sau412** [comment]
Good luck!
